# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Treatbox Cake App - Dev"
client_id = "0eacd3a621cac73517105bb9f7becc6a"
application_url = "https://927ba0c7687f.ngrok.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_products,write_assigned_fulfillment_orders,write_cart_transforms,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_shipping,write_third_party_fulfillment_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://927ba0c7687f.ngrok.app/auth/callback",
  "https://927ba0c7687f.ngrok.app/auth/shopify/callback",
  "https://927ba0c7687f.ngrok.app/api/auth/callback",
  "https://927ba0c7687f.ngrok.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "treatbox-development.myshopify.com"
