# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b9798a588d1861169aee50217de0097"
name = "Treatbox Cake App - Staging"
application_url = "https://staging.treatboxapp.codelayer.io"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "treatbox-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_products,write_assigned_fulfillment_orders,write_cart_transforms,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_shipping,write_third_party_fulfillment_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://staging.treatboxapp.codelayer.io/auth/callback",
  "https://staging.treatboxapp.codelayer.io/auth/shopify/callback",
  "https://staging.treatboxapp.codelayer.io/api/auth/callback",
  "https://staging.treatboxapp.codelayer.io/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
