# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Treatbox Cake App - Dev"
client_id = "0eacd3a621cac73517105bb9f7becc6a"
application_url = "https://d8fc-88-98-16-1.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_shipping,write_orders"

[auth]
redirect_urls = [
  "https://d8fc-88-98-16-1.ngrok-free.app/auth/callback",
  "https://d8fc-88-98-16-1.ngrok-free.app/auth/shopify/callback",
  "https://d8fc-88-98-16-1.ngrok-free.app/api/auth/callback",
  "https://d8fc-88-98-16-1.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "treatbox-development.myshopify.com"
