# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Treatbox Cake App - Dev"
client_id = "0eacd3a621cac73517105bb9f7becc6a"
application_url = "https://c3cd-88-98-16-1.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_shipping,write_orders,write_cart_transforms,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,write_fulfillments,read_locations"

[auth]
redirect_urls = [
  "https://c3cd-88-98-16-1.ngrok-free.app/auth/callback",
  "https://c3cd-88-98-16-1.ngrok-free.app/auth/shopify/callback",
  "https://c3cd-88-98-16-1.ngrok-free.app/api/auth/callback",
  "https://c3cd-88-98-16-1.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "treatbox-development.myshopify.com"
